# Default values for chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

attacher:
  name: attacher
  registry: quay.io/k8scsi
  repository: csi-attacher
  tag: v1.0.1
  pullPolicy: IfNotPresent
plugin:
  name: plugin
  registry: kubevault
  repository: csi-vault
  tag: 0.2.0
  pullPolicy: Always
provisioner:
  name: provisioner
  registry: quay.io/k8scsi
  repository: csi-provisioner
  tag: v1.0.1
  pullPolicy: IfNotPresent
clusterRegistrar:
  name: cluster-registrar
  registry: quay.io/k8scsi
  repository: csi-cluster-driver-registrar
  tag: v1.0.1
  pullPolicy: IfNotPresent
nodeRegistrar:
  name: node-registrar
  registry: quay.io/k8scsi
  repository: csi-node-driver-registrar
  tag: v1.0.1
  pullPolicy: IfNotPresent

controllerPlugin:
  name: controller

nodePlugin:
  name: node

logLevel: 3

## Annotations passed to operator pod(s).
##
annotations: {}

nameOverride: ""
fullnameOverride: ""

driverName: secrets.csi.kubevault.com
pluginAddress: /var/lib/csi/sockets/pluginproxy/csi.sock
pluginDir: /var/lib/csi/sockets/pluginproxy/

attachRequired: false

## Install AppBinding CRD
appbinding:
  # Specifies whether AppBinding CRD should be created
  create: true

## Installs pods as critical addon
## https://kubernetes.io/docs/tasks/administer-cluster/guaranteed-scheduling-critical-addon-pods/
criticalAddon: true

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi

## Node labels for pod assignment
## Ref: https://kubernetes.io/docs/user-guide/node-selection/
##
nodeSelector: {}

## Tolerations for pod assignment
## Ref: https://kubernetes.io/docs/concepts/configuration/taint-and-toleration/
##
tolerations: {}

## Affinity for pod assignment
## Ref: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#affinity-and-anti-affinity
##
affinity: {}

## Install Default RBAC roles and bindings
rbac:
  # Specifies whether RBAC resources should be created
  create: true

apiserver:
  # If true, uses kube-apiserver FQDN for AKS cluster to workaround https://github.com/Azure/AKS/issues/522 (default true)
  useKubeapiserverFqdnForAks: true
  # healthcheck configures the readiness and liveliness probes for the operator pod.
  healthcheck:
    enabled: true

# Send usage events to Google Analytics
enableAnalytics: true

monitoring:
  # specify monitoring agent (either "prometheus.io/builtin" or "prometheus.io/coreos-operator")
  agent: "none"
  # specify whether to monitor Vault CSI driver node plugin
  node: false
  # specify whether to monitor Vault CSI driver controller plugin
  controller: false
  # specify where ServiceMonitor crd will be created
  prometheus:
    namespace: ""
  serviceMonitor:
    labels: {}
