apiVersion: appcatalog.appscode.com/v1alpha1
kind: AppBinding
metadata:
  name: vaultapp
  namespace: default
spec:
  clientConfig:
    url: http://165.227.190.238:30001
    insecureSkipTLSVerify: true
  parameters:
    apiVersion: "kubevault.com/v1alpha1"
    kind: "VaultServerConfiguration"
    usePodServiceAccountForCSIDriver: "true"
    authPath: "kubernetes"
    policyControllerRole: testrole
