kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: vault-aws-storage
  annotations:
    storageclass.kubernetes.io/is-default-class: "false"
provisioner: com.vault.csi.vaultdbs
parameters:
  authRole: testrole
  secretEngine: AWS
  secretName: my-aws-creds

